/**
 * Shared PDF utilities for ForgeOps ERP
 */
const PDFDocument = require('pdfkit');

const COLORS = {
  ink:         '#0F1419',
  steel:       '#475467',
  rust:        '#B7410E',
  rule:        '#E5E5E0',
  paper:       '#FAFAF7',
  bandSuccess: '#15803D',
  bandWarn:    '#B7410E',
  bandDanger:  '#B91C1C',
};

function streamPDF(res, filename, build) {
  const doc = new PDFDocument({ size: 'A4', margin: 48, info: {
    Title: filename, Author: 'ForgeOps ERP',
  }});
  res.setHeader('Content-Type', 'application/pdf');
  res.setHeader('Content-Disposition', `inline; filename="${filename}"`);
  res.setHeader('Cache-Control', 'no-store');
  doc.pipe(res);
  build(doc);
  doc.end();
}

function header(doc, title, subtitle, refNumber, statusBadge) {
  // Top band
  doc.rect(0, 0, doc.page.width, 96).fill(COLORS.ink);
  doc.fillColor('#FAFAF7').font('Helvetica-Bold').fontSize(20).text('ForgeOps ERP', 48, 28);
  doc.font('Helvetica').fontSize(9).text('Industrial operations console', 48, 54);
  doc.fontSize(8).text(new Date().toLocaleString('en-IN'), 0, 28, { align: 'right', width: doc.page.width - 48 });

  // Title row
  doc.fillColor(COLORS.ink).font('Helvetica-Bold').fontSize(22).text(title, 48, 122);
  doc.fillColor(COLORS.steel).font('Helvetica').fontSize(11).text(subtitle, 48, 154);

  if (refNumber) {
    doc.font('Courier-Bold').fontSize(11).fillColor(COLORS.rust)
       .text(refNumber, 0, 122, { align: 'right', width: doc.page.width - 48 });
  }
  if (statusBadge) {
    const w = doc.widthOfString(statusBadge) + 16;
    doc.rect(doc.page.width - 48 - w, 152, w, 18).fillAndStroke(COLORS.paper, COLORS.ink);
    doc.fillColor(COLORS.ink).font('Helvetica-Bold').fontSize(9)
       .text(statusBadge.toUpperCase(), doc.page.width - 48 - w + 8, 158);
  }

  // Divider
  doc.moveTo(48, 188).lineTo(doc.page.width - 48, 188)
     .strokeColor(COLORS.rule).lineWidth(0.5).stroke();
  return 208; // cursor y
}

function kv(doc, x, y, label, value) {
  doc.fillColor(COLORS.steel).font('Helvetica').fontSize(8)
     .text(label.toUpperCase(), x, y, { characterSpacing: 0.5 });
  doc.fillColor(COLORS.ink).font('Helvetica-Bold').fontSize(11)
     .text(String(value ?? '—'), x, y + 12);
}

function drawTable(doc, { headers, rows, startY, colWidths, align = [] }) {
  const x0 = 48;
  const rowH = 20, headerH = 24;
  const tableWidth = colWidths.reduce((a, b) => a + b, 0);

  // Header row
  doc.rect(x0, startY, tableWidth, headerH).fill(COLORS.ink);
  headers.forEach((h, i) => {
    const cx = x0 + colWidths.slice(0, i).reduce((a, b) => a + b, 0);
    doc.fillColor('#FAFAF7').font('Helvetica-Bold').fontSize(9)
       .text(h.toUpperCase(), cx + 6, startY + 8,
             { width: colWidths[i] - 12, align: align[i] || 'left' });
  });

  let y = startY + headerH;
  rows.forEach((row, ri) => {
    if (ri % 2 === 0) doc.rect(x0, y, tableWidth, rowH).fill('#F5F4EE');
    row.forEach((cell, ci) => {
      const cx = x0 + colWidths.slice(0, ci).reduce((a, b) => a + b, 0);
      doc.fillColor(COLORS.ink)
         .font(align[ci] === 'right' ? 'Courier' : 'Helvetica').fontSize(9)
         .text(String(cell ?? ''), cx + 6, y + 6,
               { width: colWidths[ci] - 12, align: align[ci] || 'left' });
    });
    y += rowH;
  });
  return y + 8;
}

function footer(doc) {
  const y = doc.page.height - 40;
  doc.moveTo(48, y).lineTo(doc.page.width - 48, y)
     .strokeColor(COLORS.rule).lineWidth(0.5).stroke();
  doc.fillColor(COLORS.steel).font('Helvetica').fontSize(8)
     .text('Generated by ForgeOps ERP — every value derived from live database. No static fields.',
           48, y + 8, { align: 'center', width: doc.page.width - 96 });
}

module.exports = { streamPDF, header, kv, drawTable, footer, COLORS };
